baseURL = "https://komilab.org"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true
enableGitInfo = true

[build]
  writeStats = true

[minify]
  minifyOutput = true

[params]
  description = "Plateforme d'ingénierie technique Réseaux, Cybersécurité, Cloud, Infrastructure ultra Documentée."
  author = "KomiLab"
  siteTagline = "Labs et Documentation"
  linkedinURL = "https://www.linkedin.com/in/komi-mawuli-kpodohouin-866bb8155"
  githubURL = ""
  discordEnabled = false

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    guessSyntax = true
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
  difficulty = "difficulty"
  series = "series"

[outputs]
  home    = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  page    = ["HTML"]

[outputFormats.JSON]
  mediaType    = "application/json"
  baseName     = "index"
  isPlainText  = true

[sitemap]
  changefreq = "weekly"
  priority   = 0.5
  filename   = "sitemap.xml"

[languages]
  [languages.fr]
    languageName = "FR"
    weight       = 1
    contentDir   = "content"
    [languages.fr.params]
      locale = "fr_FR"
    [[languages.fr.menus.main]]
      name   = "Labs"
      url    = "/labs/"
      weight = 1
    [[languages.fr.menus.main]]
      name   = "Veille"
      url    = "/veille/"
      weight = 2
    [[languages.fr.menus.main]]
      name   = "A propos"
      url    = "/a-propos/"
      weight = 4

[security]
  enableInlineShortcodes = false
  [security.funcs]
    getenv = ["^HUGO_", "^CI$"]
